name: HAPprime
version: 0.6dev
date: 2011-06-09
description: |
    a HAP extension for small prime power groups

authors:
    - name: Paul Smith
      url: http://www.cs.st-andrews.ac.uk/~pas

maintainers:
    - name: Paul Smith
      url: http://www.cs.st-andrews.ac.uk/~pas
    - name:  The CHA Group
      url: http://hamilton.nuigalway.ie/CHA/

GAP: ">=4.7"

needed-pkgs:
    - name: "HAP"
      version: ">=1.9.3"
      url: "http://hamilton.nuigalway.ie/Hap/www"
    - name: "GAPDoc"
      version: "1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/happrime/
readme: README
packageinfo: https://gap-packages.github.io/happrime/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/happrime/releases/download/v0.6dev/happrime-0.6dev.tar.gz

abstract: |
    The <span class="pkgname">HAPPrime</span> package is an extension to the   <span class="pkgname">HAP</span> package, and implements memory-efficient   algorithms for the calculation of resolutions of small prime-power groups.

status: deposited
doc-html: doc/userguide/chap0.html
doc-pdf: doc/userguide/manual.pdf
